# Generated by Django 3.0.7 on 2020-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersupplieditem',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='orderrequesteditem',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
