# Generated by Django 3.0.7 on 2020-07-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200730_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequesteditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requested', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='ordersupplieditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_supplied', to='api.Order'),
        ),
    ]
