# Generated by Django 3.0.7 on 2020-08-05 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_entity_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='manager',
        ),
        migrations.AddField(
            model_name='entity',
            name='manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
