# Generated by Django 3.0.7 on 2020-08-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200805_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinventory',
            name='origin_supply',
        ),
        migrations.AlterField(
            model_name='ordersupplieditem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='supplierinventory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entity'),
        ),
    ]
