# Generated by Django 3.0.7 on 2020-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200817_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupplieditem',
            name='external_shipment_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersupplieditem',
            name='external_shipment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
