# Generated by Django 3.0.7 on 2020-09-16 22:51

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200817_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderrequesteditem',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
