# Generated by Django 3.0.7 on 2020-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200916_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequesteditem',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='order',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
